# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d03cdfa2f767fb7168c565610752c7369fef7a209f0ad543636943d74e6be34a776a4481b166cfbd8ac7c31c9b746269689460c1bdec64d9e198a3df069ec62

test:
  secret_key_base: ad9ff5a647dd682a7c89d92d88185eea1e1bc4c86cd2c448829e0b06a0bccbffa44370cf3334fa67a9d80435343cb35e878570b0d3f0382f84e0b0e45b57a666

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
